import { useState } from 'react';
import Head from 'next/head';
import { AiFillGithub, AiFillLinkedin, AiFillMail } from 'react-icons/ai';
import { FaPhoneAlt } from 'react-icons/fa';
import Image from 'next/image';
import frontend from '../../public/images/frontend.png';
import cleanCode from '../../public/images/cleanCode.png';
import crossPlatform from '../../public/images/crossPlatform.png';
import moe from '../../public/images/moe.png';
import projects from '../data';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
  };
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Mohamed Adel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 dark:bg-gray-800 ">
        <section className="min-h-screen">
          <Header toggleDarkMode={toggleDarkMode} />
          <div className="relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96">
            <Image src={moe} className='' />
          </div>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Mohamed Adel
            </h2>
            <h3 className="text-2xl py-2 dark:text-gray-200 md:text-3xl">
              Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-200 max-w-7xl lg:px-40 mx-auto">
              Hi there! My name is Mohamed Adel, and I am a software developer
              with a passion for creating visually appealing and functional web
              applications. With a background in computer engineering and
              experience in front-end development, I am eager to bring my skills
              and knowledge to a company that values innovation and
              collaboration. Throughout my career, I have honed my front-end
              development skills using React, HTML, CSS, and JavaScript. I am a
              proactive problem-solver with strong attention to details and
              excellent communication skills. Additionally, I am a team player
              who is always willing to learn and adapt to new technologies.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-10 py-3 text-gray-600 dark:text-gray-200 ">
            <a href="https://www.linkedin.com/in/imoedev/" target={'_blank'} className='hover:text-teal-600'>
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/imoeadel" target={'_blank'} className='hover:text-teal-600'>
              <AiFillGithub />
            </a>
          </div>
        </section>
        <section className='px-10'>
          <h3 className="flex justify-center text-3xl py-1 dark:text-gray-200 font-burtons">Services I offer</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1">
              <Image
                src={cleanCode}
                width={150}
                height={150}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Clean Code
              </h3>
              <p className="dark:text-gray-200">
                I strive to write organized, readable, and efficient code that
                adheres to industry standards and best practices. By
                consistently incorporating meaningful naming conventions and
                clear commenting, I ensure that my code is maintainable and
                easily understandable for both myself and other developers.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1">
              <Image
                src={frontend}
                width={150}
                height={150}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Frontend
              </h3>
              <p className="dark:text-gray-200">
                I offer professional frontend development services, specializing
                in creating user-friendly and visually appealing websites and
                applications. Utilizing the latest technologies and design
                principles, I bring ideas to life and deliver top-notch results
                for clients.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1">
              <Image
                src={crossPlatform}
                width={150}
                height={150}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-teal-600">
                Cross-platform
              </h3>
              <p className="dark:text-gray-200">
                I provide cross-platform development services, creating seamless
                experiences for users on various devices and platforms. From
                responsive web design to native mobile applications, I ensure
                that my clients reach their target audience no matter where they
                are.
              </p>
            </div>
          </div>
        </section>

        <section className='px-10'>
          <div>
            <h3 className="flex justify-center text-3xl py-1 font-burtons dark:text-gray-200">Projects</h3>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              {projects.map((project, index) => (
                <div className="basis-1/3 flex-1">
                  <a href={`/project/${project.slug}`}
                    className="basis-1/3 flex-1">
                      <Image
                      src={project.image}
                      className="rounded-lg object-cover w-full h-full cursor-pointer"
                    />
                    </a>
                </div>
              ))}
            </div>
          </div>
        </section>
        <h3 className="flex justify-center text-3xl py-1 font-burtons dark:text-gray-200">Let's work together</h3>


            <div className="flex flex-row items-center justify-center gap-10 py-20">
              <div className="flex flex-col items-center justify-center gap-10 py-3 text-gray-600 dark:text-teal-500 dark:border-teal-900 dark:hover:border-teal-600 w-72 h-40 transition-all duration-700 ease-in-out transform hover:scale-110 rounded-3xl border-4 border-zinc-500">
                <FaPhoneAlt className="text-5xl " />
                <p>+201067402171</p>
              </div>
              <div className="flex flex-col items-center justify-center gap-10 py-3 text-gray-600 dark:text-teal-500 dark:border-teal-900 dark:hover:border-teal-600 w-72 h-40 transition-all duration-700 ease-in-out transform hover:scale-110 rounded-3xl border-4 border-zinc-500">
                <AiFillMail className="text-5xl " />
                imoedev@gmail.com
              </div>
              
        </div>
        <Footer />
      </main>
    </div>
  );
}
